### ISSUE TITLE
undefined method `key?' for #<Lazylead::PlainCC:0x00007f4a37af0f68>   /lazylead/lib/lazylead/cc.rb:41:in `detect'

### ISSUE THREAD

**Issue by dgroup** [dgroup/lazylead#175]
```ruby
 69978365321080 rufus-scheduler intercepted an error:
  69978365321080   job:
  69978365321080     Rufus::Scheduler::CronJob "3 5 * * *" {}
  69978365321080   error:
  69978365321080     69978365321080
  69978365321080     NoMethodError
  69978365321080     undefined method `key?' for #<Lazylead::PlainCC:0x00007f4a37af0f68>
  69978365321080       /lazylead/lib/lazylead/cc.rb:41:in `detect'
  69978365321080       /lazylead/lib/lazylead/model.rb:106:in `detect_cc'
  69978365321080       /lazylead/lib/lazylead/model.rb:99:in `exec'
  69978365321080       /lazylead/lib/lazylead/schedule.rb:54:in `block in register'
  69978365321080       /usr/local/bundle/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:223:in `do_call'
  69978365321080       /usr/local/bundle/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:267:in `trigger_now'
  69978365321080       /usr/local/bundle/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:312:in `block (3 levels) in start_work_thread'
  69978365321080       /usr/local/bundle/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:315:in `block (2 levels) in start_work_thread'
  69978365321080       /usr/local/bundle/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:301:in `loop'

```

**Comment by dgroup** [comment]
@rultor release tag=`0.3.1`
