### ISSUE TITLE
NoMethodError: undefined method `attrs' for nil:NilClass         /lazylead/lib/lazylead/system/jira.rb:179:in `assignee'

### ISSUE THREAD

**Issue by dgroup** [dgroup/lazylead#239]
```
NoMethodError: undefined method `attrs' for nil:NilClass
        /lazylead/lib/lazylead/system/jira.rb:179:in `assignee'
        /lazylead/lib/lazylead/task/alert.rb:75:in `each'
        /lazylead/lib/lazylead/task/alert.rb:75:in `group_by'
        /lazylead/lib/lazylead/task/alert.rb:75:in `run'
        /lazylead/lib/lazylead/model.rb:102:in `exec'
        /lazylead/lib/lazylead/model.rb:180:in `exec'
        /lazylead/lib/lazylead/schedule.rb:50:in `block (2 levels) in register'
        /usr/local/bundle/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
        /lazylead/lib/lazylead/schedule.rb:49:in `block in register'

```

**Comment by dgroup** [comment]
assignee was `Unassigned`, cancelled
