### ISSUE TITLE
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - 

### ISSUE THREAD

**Issue by dgroup** [dgroup/lazylead#262]
```ruby
Minitest::UnexpectedError: Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - C:/Users/xxx/AppData/Local/Temp/1/d20201121-15140-76to3p
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:1459:in `rmdir'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:1459:in `block in remove_dir1'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:1473:in `platform_support'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:1458:in `remove_dir1'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:1451:in `remove'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:780:in `block in remove_entry'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:1508:in `ensure in postorder_traverse'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:1508:in `postorder_traverse'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:778:in `remove_entry'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/tmpdir-0.1.0/lib/tmpdir.rb:97:in `ensure in mktmpdir'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/tmpdir-0.1.0/lib/tmpdir.rb:97:in `mktmpdir'
    C:/nc/project/o2uk/git.src/l/lib/lazylead/task/svn/diff.rb:58:in `send_email'
    C:/nc/project/o2uk/git.src/l/lib/lazylead/task/svn/diff.rb:51:in `run'
    C:/nc/project/o2uk/git.src/l/test/lazylead/task/svn/diff_test.rb:100:in `block in <class:DiffTest>'
```

**Comment by dgroup** [comment]
@rultor release tag=`0.6.1`
